name: Deploy Website to InfinityFree

on:
  push:
    branches:
      - main  # Robot ini akan jalan setiap kamu push ke branch main / master

jobs:
  web-deploy:
    name: Sync Files
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Sync files to InfinityFree via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: htdocs/  # File akan otomatis dimasukkan ke dalam folder htdocs
